### ISSUE TITLE
老哥，知道怎么样搞宥马云端提交数据吗

### ISSUE THREAD

**Issue by su1904** [flipped-1121/UMengUserInfo#1]
老哥，知道怎么样搞宥马云端提交数据吗

**Comment by flipped-1121** [comment]
> 老哥，知道怎么样搞宥马云端提交数据吗

我写了一个测试，[测试链接](https://fuckym.kangblogs.top/user)

**Comment by su1904** [comment]
老哥，这个打不打算开源？

**Comment by su1904** [comment]
> 

不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交

**Comment by flipped-1121** [comment]
> > 
> 
> 不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交

就是写的数据动态变化，不会少0.02刚好不达标吧🤔

**Comment by flipped-1121** [comment]
> 老哥，这个打不打算开源？

再考虑，写着玩的，学习使用

**Comment by su1904** [comment]
> 



> > > 
> > 
> > 
> > 不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交
> 
> 就是写的数据动态变化，不会少0.02刚好不达标吧🤔

可以达标但是如果之前的数据减0.02刚好不到2公里，也会提交但是会少0.02

**Comment by flipped-1121** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > 不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交
> > 
> > 
> > 就是写的数据动态变化，不会少0.02刚好不达标吧🤔
> 
> 可以达标但是如果之前的数据减0.02刚好不到2公里，也会提交但是会少0.02

感谢反馈，我添加个判断解决这个问题

**Comment by su1904** [comment]
> > 老哥，这个打不打算开源？
> 
> 再考虑，写着玩的，学习使用

> > 老哥，这个打不打算开源？
> 
> 再考虑，写着玩的，学习使用

老哥源码能分享我一份我，我也借鉴一下，搞一个

**Comment by su1904** [comment]
> > > 
> > 
> > 
> > > > > 
> > > > 
> > > > 
> > > > 不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交
> > > 
> > > 
> > > 就是写的数据动态变化，不会少0.02刚好不达标吧🤔
> > 
> > 
> > 可以达标但是如果之前的数据减0.02刚好不到2公里，也会提交但是会少0.02
> 
> 感谢反馈，我添加个判断解决这个问题

感觉可以从20条左右取一条随机提交一条比较保险

**Comment by flipped-1121** [comment]
> > > > 
> > > 
> > > 
> > > > > > 
> > > > > 
> > > > > 
> > > > > 不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交
> > > > 
> > > > 
> > > > 就是写的数据动态变化，不会少0.02刚好不达标吧🤔
> > > 
> > > 
> > > 可以达标但是如果之前的数据减0.02刚好不到2公里，也会提交但是会少0.02
> > 
> > 
> > 感谢反馈，我添加个判断解决这个问题
> 
> 感觉可以从20条左右取一条随机提交一条比较保险

当时考虑到有的人跑的次数可能比较少，这个确实需要处理一下，后期有时间再搞

**Comment by su1904** [comment]
> 

当然，也可以考虑把数据提前存储到数据库，用的时候随机提交一条，这样的话就只能一个学校的使用，局限性也很大

**Comment by su1904** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 不对啊，老哥，你这个测试的提交数据会少0.02公里，。但是能提交
> > > > > 
> > > > > 
> > > > > 就是写的数据动态变化，不会少0.02刚好不达标吧🤔
> > > > 
> > > > 
> > > > 可以达标但是如果之前的数据减0.02刚好不到2公里，也会提交但是会少0.02
> > > 
> > > 
> > > 感谢反馈，我添加个判断解决这个问题
> > 
> > 
> > 感觉可以从20条左右取一条随机提交一条比较保险
> 
> 当时考虑到有的人跑的次数可能比较少，这个确实需要处理一下，后期有时间再搞

老哥，这个可以根据你开源的这个信息展示，写成云端提交数据吗？
