### ISSUE TITLE
老哥，能问一下那个提交数据的接口是哪一个？，抓了半天也没有抓出来

### ISSUE THREAD

**Issue by su1904** [flipped-1121/UMengUserInfo#2]
老哥，能问一下那个提交数据的接口是哪一个？，抓了半天也没有抓出来

**Comment by flipped-1121** [comment]
> 老哥，能问一下那个提交数据的接口是哪一个？，抓了半天也没有抓出来

多抓抓就有了

**Comment by su1904** [comment]
> > 老哥，能问一下那个提交数据的接口是哪一个？，抓了半天也没有抓出来
> 
> 多抓抓就有了

老哥，那能问一下这个思路是怎么样的

**Comment by flipped-1121** [comment]
> > > 老哥，能问一下那个提交数据的接口是哪一个？，抓了半天也没有抓出来
> > 
> > 
> > 多抓抓就有了
> 
> 老哥，那能问一下这个思路是怎么样的

既然可以抓包，就一定能抓到软件运行过程中想要的数据包（包括但不限于数据上传接口），善用工具
抓包流程也没什么思路可言吧
